### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by azzaea** [bd2kccd/causal-rest-api#24]
Hello,
I'm trying to install the `Causal-Rest-API` as per this tutorial [here](https://bd2kccd.github.io/docs/causal-rest-api/#dependencies). `Causal-Web` is now installed and running, and both `ccd-commons` and `ccd-db` are in place. 

The installation step for `causal-rest-api` fails with the error below, which I assume to mean missing the `tetrad-lib-6.4.0.jar`. I tried to download a ready file from [here](https://cloud.ccd.pitt.edu/nexus/content/repositories/releases/edu/cmu/tetrad-lib/6.4.0/) and put it in my `workspace/lib` directory- which failed. Then, I also tried to compile tetrad from [this source](https://github.com/cmu-phil/tetrad/releases/tag/6.4.0); all to no avail. I'm not sure what I'm missing, and would greatly appreciate your help.

Thank you in advance,
Azza

```
$ mvn clean package
:
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.242 s
[INFO] Finished at: 2019-09-03T08:27:07+02:00
[INFO] Final Memory: 24M/267M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project causal-rest-api: Could not resolve dependencies for project edu.pitt.dbmi.ccd:causal-rest-api:jar:1.0.0: Failed to collect dependencies at edu.cmu:tetrad-lib:jar:6.4.0-SNAPSHOT: Failed to read artifact descriptor for edu.cmu:tetrad-lib:jar:6.4.0-SNAPSHOT: Could not transfer artifact edu.cmu:tetrad-lib:pom:6.4.0-SNAPSHOT from/to ccd-releases (https://cloud.ccd.pitt.edu/nexus/content/repositories/releases/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by espinoj** [comment]
Azza,  try again now as we had to renew our SSL certificates for that server.

**Comment by azzaea** [comment]
Excellent! It works like charm. Closing this issue
